services:
  funpay_monitor:
    container_name: funpay_monitor
    image: nekromant322/funpay-monitor:latest
    depends_on:
      - funpay_monitor_db
    environment:
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8081:8080"
    networks:
      - postgres
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 10s
      timeout: 5s
      retries: 6

  funpay_monitor_db:
    container_name: funpay_monitor_db
    image: postgres
    environment:
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

  selenium-chrome:
    image: selenium/standalone-chrome:latest
    container_name: selenium-chrome
    ports:
      - "4444:4444"
    networks:
      - postgres
    shm_size: 2g

networks:
  postgres:
    driver: bridge

volumes:
  postgres:

