services:
  funpay_monitor:
    container_name: funpay_monitor
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - postgres
    volumes:
      - maven-repo:/root/.m2
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

  funpay_monitor_db:
    container_name: funpay_monitor_db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  maven-repo:

