spring:
  application:
    name: funpay-monitor

  datasource:
    hikari:
      connectionTimeout: '20000'
      maximumPoolSize: '5'
    url: jdbc:postgresql://localhost:5432/java_test_con
    username: postgres
    password: 1234
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
app:
  scrapRate: '60000'

google:
  auth-path: google_sheet_auth.json
