spring:
  application:
    name: funpay-monitor
  datasource:
    hikari:
      connectionTimeout: '20000'
      maximumPoolSize: '5'
    url: jdbc:postgresql://funpay_monitor_db:5432/postgres
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:1234}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
app:
  scrapRate: '3600000'

google:
  private-key-id: ${GOOGLE_PRIVATE_KEY_ID}
  private-key: ${GOOGLE_PRIVATE_ID}



