spring:
  application:
    name: funpay-monitor

  datasource:
    hikari:
      connectionTimeout: '20000'
      maximumPoolSize: '5'
    url: jdbc:postgresql://localhost:5432/java_test_con
    username: postgres
    password: 1234
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
app:
  scrapRate: '60000'
  webDriver: C:\Users\world\Desktop\java cringe\FunpayMonitor\drivers\chromedriver_for_win.exe

  selenium:
    url: http://selenium-chrome:4444/wd/hub
