spring:
  profiles:
    active: dev


cache:
  exchange-rate:
    expire:
      after-write: 20
      time-unit: minutes

binance:
  currency-rate-url: https://api.binance.com/api/v3/ticker/price?symbol=