spring:
  application:
    name: funpay-monitor
  datasource:
    hikari:
      connectionTimeout: '20000'
      maximumPoolSize: '5'
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:changeme}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create

cache:
  exchange-rate:
    expire:
      after-write: 20
      time-unit: minutes

binance:
  currency-rate-url: https://api.binance.com/api/v3/ticker/price?symbol=USDTRUB

funpay:
  base-url: https://funpay.com/lots/2434/

app:
  scrapRate: '60000'