spring:
  profiles:
    active: dev

cache:
  exchange-rate:
    expire:
      after-write: 20
      time-unit: minutes

binance:
  currency-rate-url: https://api.binance.com/api/v3/ticker/price?symbol=USDTRUB

funpay:
  base-url: https://funpay.com/lots/2434/
  currency-cookies: usd


google:
  poe-divine-id: 109VJFvRRgmaQfu_4C8y8G4Ro-ejKVkXLGX3dmFEGgoc