spring:
  application:
    name: funpay-monitor
  datasource:
    hikari:
      connectionTimeout: '20000'
      maximumPoolSize: '5'
    url: jdbc:postgresql://${DATABASE_DOMAIN:localhost}:5432/${DATABASE_NAME:java_test_con}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:1234}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
app:
  scrapRate: '60000'
