name: Build image && run new version on server

on:
  push:
    branches:
      - master


jobs:

  #в скрипте надо:
  #собрать образ
  #пушнуть в дкоерхаб
  #скопировать композ на сервер
  #запустить на сервере новую версию приложения

  #* не забыть выставить лимит 50мб на логи в композе, иначе засрешь весь диск
  #по оперативе тоже неплохо бы в 250мб уместиться через параметры жвм

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install -B -DskipTests

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: nekromant322
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # 1. Устанавливаем env-переменные из secrets
      - name: Setup environment
        run: |
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> $GITHUB_ENV
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> $GITHUB_ENV
          echo "GOOGLE_PRIVATE_KEY_ID=${{ secrets.GOOGLE_PRIVATE_KEY_ID }}" >> $GITHUB_ENV
          echo "GOOGLE_PRIVATE_ID=${{ secrets.GOOGLE_PRIVATE_ID }}" >> $GITHUB_ENV

      # 2. Генерируем docker-compose.yml из шаблона
      - name: Generate docker-compose from template
        run: |
          sudo apt-get update && sudo apt-get install -y gettext-base
          envsubst < docker-compose.yaml > docker-compose.generated.yaml
          mv docker-compose.generated.yaml docker-compose.yaml

      - name: Build and Push to Dockerhub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: nekromant322/funpay-monitor:latest

      - name: Copy docker-compose to server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: 194.87.99.49
          username: github
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "docker-compose.yaml"
          target: "~/funpay-monitor/"

      - name: docker compose up
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: 194.87.99.49
          username: github
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            set -e  # Прерываем выполнение при ошибках 
            cd ~/funpay-monitor
            
            echo " Останавливаем и удаляем старые контейнеры..."
            docker compose stop funpay_monitor
            
            
            echo " Запускаем новую версию контейнеров..."
            docker-compose pull
            docker-compose up -d --remove-orphans  --wait